"""001 True 

Revision ID: 5397807a514e
Revises: 9abd9b1e5660
Create Date: 2023-12-26 13:28:30.081343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5397807a514e'
down_revision: Union[str, None] = '9abd9b1e5660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tank_numbertank', table_name='tank')
    op.drop_table('tank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tank',
    sa.Column('numbertank', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('numbertank', name='tank_pkey')
    )
    op.create_index('ix_tank_numbertank', 'tank', ['numbertank'], unique=False)
    # ### end Alembic commands ###
