"""1000

Revision ID: 9abd9b1e5660
Revises: 8bbb61676f56
Create Date: 2023-12-26 10:38:34.099613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abd9b1e5660'
down_revision: Union[str, None] = '8bbb61676f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tank',
    sa.Column('numbertank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('numbertank')
    )
    op.create_index(op.f('ix_tank_numbertank'), 'tank', ['numbertank'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tank_numbertank'), table_name='tank')
    op.drop_table('tank')
    # ### end Alembic commands ###
