"""Youre here

Revision ID: e82f9ae366bd
Revises: 
Create Date: 2023-12-26 09:55:08.020379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82f9ae366bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items2_id'), 'items2', ['id'], unique=False)
    op.create_index(op.f('ix_items2_name'), 'items2', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items2_name'), table_name='items2')
    op.drop_index(op.f('ix_items2_id'), table_name='items2')
    op.drop_table('items2')
    # ### end Alembic commands ###
